-- Seed the first real POI slice for the MVP route: Catedral de Jaen.

INSERT INTO pois (
  id,
  route_id,
  slug,
  name,
  description,
  status,
  latitude,
  longitude,
  access_notes,
  indoor_mode,
  display_order,
  created_at,
  updated_at
) VALUES (
  'poi-catedral-de-jaen',
  'route-jaen-echoes-of-stone',
  'catedral-de-jaen',
  'Cathedral of Jaén',
  'A monumental Renaissance cathedral in the heart of Jaén, where sacred architecture, hidden stone details and local legends make the city’s history feel alive.',
  'published',
  37.765738,
  -3.789518,
  'Located in Plaza de Santa María. Some objectives may require access to the cathedral interior, so opening hours and ticket availability should be checked before visiting.',
  1,
  0,
  '2026-06-04T00:00:00.000Z',
  '2026-06-04T00:00:00.000Z'
);

INSERT INTO visual_objectives (
  id,
  poi_id,
  slug,
  title,
  description,
  status,
  target_type,
  gps_radius_meters,
  difficulty,
  indoor_mode,
  display_order,
  created_at,
  updated_at
) VALUES
(
  'objective-catedral-de-jaen-estatua-san-fernando',
  'poi-catedral-de-jaen',
  'estatua-san-fernando',
  'Statue of Saint Ferdinand',
  'Find the statue of Saint Ferdinand, the Christian king linked to the conquest of Jaén and one of the key historical figures behind the city’s medieval memory.',
  'published',
  'statue',
  20,
  'easy',
  0,
  0,
  '2026-06-04T00:00:00.000Z',
  '2026-06-04T00:00:00.000Z'
),
(
  'objective-catedral-de-jaen-mona-catedral-jaen',
  'poi-catedral-de-jaen',
  'mona-catedral-jaen',
  'Cathedral Monkey',
  'Find the small monkey sculpture wearing a turban on the exterior of Jaén Cathedral, one of the building’s strangest and most memorable hidden details.',
  'published',
  'architectural_detail',
  3,
  'hard',
  0,
  1,
  '2026-06-04T00:00:00.000Z',
  '2026-06-04T00:00:00.000Z'
),
(
  'objective-catedral-de-jaen-placa-santa-catalina-coro',
  'poi-catedral-de-jaen',
  'placa-santa-catalina-coro',
  'Saint Catherine Choir Panel',
  'Find the wooden panel inside the choir stalls depicting Saint Catherine, a small decorative detail hidden among the carved seats of Jaén Cathedral.',
  'published',
  'decorative_panel',
  5,
  'medium',
  1,
  2,
  '2026-06-04T00:00:00.000Z',
  '2026-06-04T00:00:00.000Z'
),
(
  'objective-catedral-de-jaen-organo-catedral-jaen',
  'poi-catedral-de-jaen',
  'organo-catedral-jaen',
  'Cathedral Organ',
  'Find the cathedral organ, one of the most recognisable interior features of Jaén Cathedral, standing out through its pipes, scale and decorative presence.',
  'published',
  'architectural_detail',
  12,
  'easy',
  1,
  3,
  '2026-06-04T00:00:00.000Z',
  '2026-06-04T00:00:00.000Z'
),
(
  'objective-catedral-de-jaen-tumba-don-alonso-suarez',
  'poi-catedral-de-jaen',
  'tumba-don-alonso-suarez',
  'Tomb of Don Alonso Suárez',
  'Find the tomb of Don Alonso Suárez de la Fuente del Sauce, known as El Insepulto, one of the most intriguing funerary details inside Jaén Cathedral.',
  'published',
  'tomb',
  3,
  'hard',
  1,
  4,
  '2026-06-04T00:00:00.000Z',
  '2026-06-04T00:00:00.000Z'
);
