-- Seed the second real POI slice for the MVP route: Arab Baths of Jaen.

INSERT INTO pois (
  id,
  route_id,
  slug,
  name,
  description,
  status,
  latitude,
  longitude,
  access_notes,
  indoor_mode,
  display_order,
  created_at,
  updated_at
) VALUES (
  'poi-banos-arabes-jaen',
  'route-jaen-echoes-of-stone',
  'banos-arabes-jaen',
  'Arab Baths of Jaén',
  'One of Jaén’s most remarkable heritage sites, hidden beneath the Palace of Villardompardo and preserving the memory of the city’s Andalusian past.',
  'published',
  37.7710822,
  -3.7940612,
  'Located inside the Palace of Villardompardo, in Plaza Santa Luisa de Marillac. Interior access is required, so opening hours should be checked before visiting.',
  1,
  1,
  '2026-06-04T00:00:00.000Z',
  '2026-06-04T00:00:00.000Z'
);

INSERT INTO visual_objectives (
  id,
  poi_id,
  slug,
  title,
  description,
  status,
  target_type,
  gps_radius_meters,
  difficulty,
  indoor_mode,
  display_order,
  created_at,
  updated_at
) VALUES
(
  'objective-banos-arabes-jaen-fachada-palacio-villardompardo',
  'poi-banos-arabes-jaen',
  'fachada-palacio-villardompardo',
  'Palace of Villardompardo Façade',
  'Find the exterior façade of the Palace of Villardompardo, the historic building that houses the Arab Baths of Jaén beneath its walls.',
  'published',
  'facade',
  20,
  'easy',
  0,
  0,
  '2026-06-04T00:00:00.000Z',
  '2026-06-04T00:00:00.000Z'
),
(
  'objective-banos-arabes-jaen-pinturas-recibidor-banos-arabes',
  'poi-banos-arabes-jaen',
  'pinturas-recibidor-banos-arabes',
  'Arab Baths Entrance Paintings',
  'Find the original paintings in the entrance area of the Arab Baths, before reaching the cold room, where visitors once prepared to access the bathing spaces.',
  'published',
  'decorative_painting',
  3,
  'easy',
  1,
  1,
  '2026-06-04T00:00:00.000Z',
  '2026-06-04T00:00:00.000Z'
),
(
  'objective-banos-arabes-jaen-piscina-sala-templada-banos-arabes',
  'poi-banos-arabes-jaen',
  'piscina-sala-templada-banos-arabes',
  'Warm Room Central Pool',
  'Find the central pool in the warm room of the Arab Baths, the space where visitors would have spent most of their time during the bathing ritual.',
  'published',
  'pool',
  3,
  'easy',
  1,
  2,
  '2026-06-04T00:00:00.000Z',
  '2026-06-04T00:00:00.000Z'
),
(
  'objective-banos-arabes-jaen-columnas-ala-rey-ali',
  'poi-banos-arabes-jaen',
  'columnas-ala-rey-ali',
  'King Ali’s Wing Columns',
  'Find the columns in the king’s wing of the Arab Baths, the place linked to the death of King Ali and the legend of his lingering ghost.',
  'published',
  'architectural_detail',
  2,
  'medium',
  1,
  3,
  '2026-06-04T00:00:00.000Z',
  '2026-06-04T00:00:00.000Z'
),
(
  'objective-banos-arabes-jaen-tinajas-agua-sala-caliente',
  'poi-banos-arabes-jaen',
  'tinajas-agua-sala-caliente',
  'Hot Room Water Jars',
  'Find the water jars in the hot room of the Arab Baths, the most therapeutic space of the complex, associated with medicinal bathing practices inspired by Galenic tradition.',
  'published',
  'historic_object',
  3,
  'easy',
  1,
  4,
  '2026-06-04T00:00:00.000Z',
  '2026-06-04T00:00:00.000Z'
);
